apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door2
  template:
    metadata:
      labels:
        app: door2
    spec:
      containers:
        - name: door2
          args: ["weather", "20", "redis-service:6379", "The weather is going to be good :-)"]
          image: eu.gcr.io/eades-273019/door1:v5
