apiVersion: apps/v1
kind: Deployment
metadata:
  name: door3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door3
  template:
    metadata:
      labels:
        app: door3
    spec:
      containers:
        - name: door3
          args: ["sports", "300", "redis-service:6379", "Latest! Winners vs. Loosers 1:5"]
          image: eu.gcr.io/eades-273019/door1:v7
