apiVersion: apps/v1
kind: Deployment
metadata:
  name: door1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door1
  template:
    metadata:
      labels:
        app: door1
    spec:
      containers:
        - name: door1
          args: ["News", "10", "redis-service:6379", "No news! Is good news ;-)"]
          image: eu.gcr.io/eades-273019/door1:v8
