apiVersion: apps/v1
kind: Deployment
metadata:
  name: door1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door1
  template:
    metadata:
      labels:
        app: door1
    spec:
      containers:
        - name: door1
          args: ["1", "10", "redis-service:6379"]
          image: <your docker hub name>/door:v1
