apiVersion: v1
kind: Service
metadata:
  name: seccon-service
  labels:
    app: seccon-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  selector:
    app: seccon
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seccon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seccon
  template:
    metadata:
      labels:
        app: seccon
    spec:
      containers:
        - name: seccon
          image: eu.gcr.io/eades-273019/seccon:v2
          args: ["redis-service:6379", "2000", "50", "News1", "weather2", "sports3"]
          ports:
          - containerPort: 8080
