apiVersion: v1
kind: Service
metadata:
  name: atn-service
  labels:
    app: atn-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31916
  selector:
    app: atn
  type: NodePort
