apiVersion: v1
kind: Service
metadata:
  name: nf-service
  labels:
    name: nf-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: nf
  type: ClusterIP
