apiVersion: v1
kind: Service
metadata:
  name: wf-service
  labels:
    name: wf-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wf
  type: ClusterIP
