apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf
  template:
    metadata:
      labels:
        app: wf
    spec:
      containers:
        - name: wf
          image: eu.gcr.io/eades-273019/weatherfetcher:v1
